work_dir:  ./work_dir/master/ntu60_cv/aimclr_joint/finetune_eval/label_percent_0.01

# weights: /data/gty/released_model/ntu60_xview_joint.pt
weights:  /mnt/netdisk/linlilang/NoisyDINO/work_dir/bottleneck/ntu60_cv/aimclr_joint/pretext/pretrain_150/queue_65536/topk_8192/ks_0.5/noise_0.05/clip_1.0/mask_predict/mask_forward/graph_aug/qscore_sim/gpu_4/epoch350_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue, mu, kappa, alpha, encoder_q.slot_attn, to_q, to_v, to_k, slot_attn, decoder_r, encoder_q.dense, decoder_m, prototypes]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_semi
train_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU60_frame50/xview/train_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU60_frame50/xview/val_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: True
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [10,50]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 80
stream: 'joint'

# log
save_interval: -1
eval_interval: 5
# knn_interval: -1
