work_dir:  ./work_dir/ntu60_cv/actclr_motion/finetune_eval

# weights: /data/gty/released_model/ntu60_xview_joint.pt
weights:  ./work_dir/ntu60_cv/actclr_motion/pretext/epoch300_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: ./CrosSCLR/data/NTU60_frame50/xview/train_position.npy
  label_path: ./CrosSCLR/data/NTU-RGB-D/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: ./CrosSCLR/data/NTU60_frame50/xview/val_position.npy
  label_path: ./CrosSCLR/data/NTU-RGB-D/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.actclr.actclr
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: True
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [10,50]

# training
device: [2]
batch_size: 128
test_batch_size: 128
num_epoch: 80
stream: 'motion'

# log
save_interval: -1
eval_interval: 5
knn_interval: -1
