work_dir:  ./work_dir/master/ntu120_cv/aimclr_bone/finetune_eval

# weights: /data/gty/released_model/ntu120_xset_joint.pt
weights:  ./work_dir/master/ntu120_cv/aimclr_bone/pretext/epoch300_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU120_frame50/xset/train_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D_120/xset/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU120_frame50/xset/val_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D_120/xset/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 120
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: True
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [30,50]

# training
device: [4]
batch_size: 128
test_batch_size: 128
num_epoch: 80
stream: 'bone'

# log
save_interval: -1
eval_interval: 5
knn_interval: -1
