work_dir: ./work_dir/ntu60_cv/actclr_bone/pretext
weights:  ./AimCLR-main/work_dir/ntu60_cv/aimclr_bone/pretext/epoch300_model.pt

ignore_weights: [queue]
rename_weights: [encoder_q.encoder_k]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: ./CrosSCLR/data/NTU60_frame50/xview/train_position.npy
  label_path: ./CrosSCLR/data/NTU-RGB-D/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# memory feeder for knn
mem_train_feeder: feeder.ntu_feeder.Feeder_single
mem_train_feeder_args:
  data_path: ./CrosSCLR/data/NTU60_frame50/xview/train_position.npy
  label_path: ./CrosSCLR/data/NTU-RGB-D/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True
mem_test_feeder: feeder.ntu_feeder.Feeder_single
mem_test_feeder_args:
  data_path: ./CrosSCLR/data/NTU60_frame50/xview/val_position.npy
  label_path: ./CrosSCLR/data/NTU-RGB-D/xview/val_label.pkl 
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.actclr.actclr
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: True
  feature_dim: 128
  queue_size: 65536
  momentum: 0.999
  Temperature: 0.07
  mlp: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [250]

# training
device: [9]
batch_size: 128
test_batch_size: 128
num_epoch: 300
start_epoch: 0
stream: 'bone'

# nearest neighbor mining
topk: 1
mining_epoch: 500

# log
save_interval: 5
eval_interval: -1

knn_interval: 5
knn_k: [10, 20, 40]
knn_classes: 60
knn_t: 0.1
KNN_show: [50, 100, 150, 200, 250, 300]