work_dir: /mnt/netdisk/linlilang/AimCLR-main/work_dir/ntu120_cv/aimclr_bone/pretext/dim_512

# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU120_frame50/xset/train_position.npy
  label_path: /mnt/netdisk/linlilang/CrosSCLR/data/NTU-RGB-D_120/xset/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: True
  feature_dim: 256
  queue_size: 32768
  momentum: 0.999
  Temperature: 0.07
  mlp: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  hidden_dim: 512
  num_class: 120
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [250]

# training
device: [4]
batch_size: 128
test_batch_size: 128
num_epoch: 300
start_epoch: 0
stream: 'bone'

# nearest neighbor mining
topk: 1
mining_epoch: 150

# log
save_interval: 5
eval_interval: -1
