work_dir:  ./work_dir/ntu60_cv/actclr_joint/linear_eval/

# weights: /data/gty/released_model/ntu60_xview_joint.pt
weights:  ./work_dir/ntu60_cv/actclr_joint/pretext/epoch300_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue, predictor]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: ./SkeleMixCLR-main/data/Base/NTU60_frame64/xview/train_position.npy
  label_path: ./CrosSCLR/data/NTU-RGB-D/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: ./SkeleMixCLR-main/data/Base/NTU60_frame64/xview/val_position.npy
  label_path: ./CrosSCLR/data/NTU-RGB-D/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.actclr.actclr
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 24.
optimizer: SGD
step: [80]

# training
device: [4]
batch_size: 1024
test_batch_size: 1024
num_epoch: 5
stream: 'joint'

# log
save_interval: -1
eval_interval: 5
knn_interval: -1
